version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./app:/app
    command: >
      sh -c " ls &&
             python3 manage.py migrate django_celery_beat &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  celery-worker:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: