# Generated by Django 4.0.3 on 2022-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.RunSQL("INSERT INTO public.news_symbol (id, name, full_name, description, url) VALUES (1, 'AAPL', "
                          "'Apple Inc.', 'Apple', "
                          "'https://feeds.finance.yahoo.com/rss/2.0/headline?s=AAPL&region=US&lang=en-US');"
                          "INSERT INTO public.news_symbol (id, name, full_name, description, url) VALUES (2, 'TWTR', "
                          "'Twitter', 'Twitter', "
                          "'https://feeds.finance.yahoo.com/rss/2.0/headline?s=TWTR&region=US&lang=en-US');"
                          "INSERT INTO public.news_symbol (id, name, full_name, description, url) VALUES (3, 'GC=F', "
                          "'Gold Futures', 'Gold Futures', "
                          "'https://feeds.finance.yahoo.com/rss/2.0/headline?s=GC=F&region=US&lang=en-US');"
                          "INSERT INTO public.news_symbol (id, name, full_name, description, url) VALUES (4, 'INTC', "
                          "'Intel Corporation', 'Intel Corporation', "
                          "'https://feeds.finance.yahoo.com/rss/2.0/headline?s=INTC&region=US&lang=en-US');")
    ]
