# Generated by Django 3.0.1 on 2022-04-07 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pubDate',
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 20, 58, 48, 599194, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
