# Generated by Django 3.0.1 on 2022-04-07 21:10

from django.db import migrations, models
from django.template.defaultfilters import slugify

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220407_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
