# Generated by Django 3.0.1 on 2022-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='symbol',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
