# Generated by Django 3.0.1 on 2022-04-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
    ]
